### ISSUE TITLE
Book  Width

### ISSUE THREAD

**Issue by taniaMashenko** [khalid-a-omar/Polyfish#1]
Hi Omar,
I want to extend my thanks and appreciation for your time and effort in adding different ideas and flavor to Stockfish.
the engine plays moves outside of the book when increasing  Book  Width to 2 or 3.
Friendly request:
Could you please add support for embedded ( integrated)  polyglot chess book, I would like to increase the variety of opening by adding a tiny 2 moves book in my engine testing tournaments

**Comment by khalid-a-omar** [comment]
Hello,

It is very unlikely that the engine will make book moves not from the book regardless of the book width setting. If that was to happen then I expect a crash rather than a valid move being made.

Having said that, please check the specific position(s) using the **poly** command to see if the book has moves or not. If you still believe the problem is there then please send me the book and the position fen string and I will gladly fix the problem.

Adding embedded book support is not on my todo list for now. I believe you can manage with setting the book name in the engine options without issues.

**Comment by Frosty54** [comment]
Hello, Omar. Thanks for great Polyfish engine and a lot of hard work that you made. Can you make please latest version of Eman on android please. My email: `<email address removed>`

**Comment by khalid-a-omar** [comment]
Hello, Eman can only be compiled on Windows, the code is just not compatible and I don't have bandwidth to rewrite the code!
Besides, I'm no longer distributing Eman publicly. Sorry

**Comment by Frosty54** [comment]
Thanks for answer. Sorry for worry.

пн, 3 апр. 2023 г., 19:54 Khalid Omar ***@***.***>:

**Comment by Frosty54** [comment]
Hello, I saw some  interesting options in your engine and I'm interested
how to implement Middlegame & Endgame NN options?

**Comment by khalid-a-omar** [comment]
For the sake of clarity. Please create a new issue if you are not commenting on the existing one!

**Comment by Frosty54** [comment]
Contact me via email

**Comment by khalid-a-omar** [comment]
If you want to discuss something related to Polyfish then I prefer to discuss here on github. Please create a new issue instead of adding a comment to an existing and unrelated issue
