### ISSUE TITLE
Book does not load?

### ISSUE THREAD

**Issue by perfectN00b** [khalid-a-omar/Polyfish#4]
I have a question... Either it doesn't work, or I don't understand it. If I enter a file instead of "<empty>", for example "book.bin", then this is not loaded. The file is of course in the same folder as the EXE. What am I doing wrong?

**Comment by khalid-a-omar** [comment]
Can you try the following?

1. Run the engine by double-clicking on the executable
2. Type `setoption name Book 1 File value Book.bin`
3. Type `poly`
4. Take a screenshot of what you see and post it here

The following is an example of what I see on my computer when typing the same commands:

![image](https://user-images.githubusercontent.com/20900472/164910495-4b257f9f-d972-4061-bdb2-c68384a69249.png)

**Comment by perfectN00b** [comment]
Thanks for the quick reply.

Am new here. How do I upload screenshots? After starting the EXE:

```
Polyglot book 1: book1.bin
No book loaded
Polyglot book 2: book2.bin
No book loaded
```

and after your command:

```
info string Book file opened successfully: book1.bin
[...]
Polyglot book 1: book1.bin
1 : e2e4 , count: 31590
2 : d2d4 , count: 26234
3 : g1f3 , count: 9667
4 : c2c4 , count: 5865
5 : b2b3 , count: 622
6 : g2g3 , count: 380
7 : f2f4 , count: 133

Polyglot book 2: book2.bin
No book loaded
```


Does this mean that the file is intentionally not loaded after startup?

**Comment by khalid-a-omar** [comment]
No need for a screenshot, the data you posted is good enough :)

I see the book is loaded successfully and it has moves for the start position.

What makes you think the book is not loaded?

**Comment by perfectN00b** [comment]
I thought the books would load immediately after launch. In Banksia GUI and other GUIs I found that you have to manually find the path. If I specify the file right away in the UCI setting, it is not loaded in the GUI. I would like to understand why this is.

**Comment by khalid-a-omar** [comment]
Polyfish will find the book in the same directory if the filename is configured without the full path.

I'm not familiar with Banksia GUI, but it seems it is capable of loading the book itself? (i.e., the engine is not the one loading and handling the book). If this is true, then I guess this is a Banksia GUI problem.

To be safe, configuring the book with full path is better if you find that to be working.

**Comment by perfectN00b** [comment]
The problem also exists with Fritz 17 and 15 (I don't have other versions). I suspected the following:

If the entered value corresponds to the default, it is not executed by the corresponding GUI. However, the Banksia log showed me that it sends the command. 

I would have liked to fix the problem by having the engine load the books itself after startup and not wait for an external command. After all, I used Polyfish so that one could have books. :)

**Comment by khalid-a-omar** [comment]
On my computer, entering the book file name (example: Book.bin) or the full book path (example: C:\Path\To\Book.bin) works fine with Fritz 17

I can't comment much about entering the value that corresponds to the default. The logic is going to depend on the GUI being used. But, since you mentioned that Banksia log shows the command being sent, what does it show after that? Do you see the engine printing `info string Book file opened successfully: book1.bin` or `info string Could not open book file: Book.bin`

Having polyglot load the book file automatically is not possible without modifying the code.

**Comment by perfectN00b** [comment]
> But, since you mentioned that Banksia log shows the command being sent, what does it show after that?

Nothing, unfortunately.

But if the books don't load automatically right after startup, it doesn't matter. With the GUIs I have to enter it manually, no matter if I specify a relative or absolute path. Only Arena seems to do it correctly.

Can you maybe give me a clue where I would have to intervene in the code? So about:

on_book(0, "book1.bin");

...or so at some place. Then I can experiment further.

Maybe a few words why I want this.

1. i access the AI from different GUIs and i don't want to have to set this extra in each GUI.
2. i want to experiment with different books per ELO. I.e. if I set Elo 1500, that a different book is loaded than at 1600 (as an example). Or take characters right away. If you enter "Omar" it is 2850 Elo and has a leet.bin. :P

But these are just gimmicks. ^^

**Comment by khalid-a-omar** [comment]
I'm sure there must be a workaround for the GUI's you are using. I never ran in such a trouble when using Fritz or InfinityChess (I did not try other GUI's).

Although it is possible, I do not recommend changing the code to load certain books automatically.

If you insist on doing it, then one way of doing it is to modify `main.cpp` to add the following line(s) after `Eval::NNUE::init();`

```
Options["Book 1 File"] = std::string("C:\\Path\\To\\Book1.bin");
Options["Book 2 File"] = std::string("Book2.bin"); //Assuming Book2.bin is in the same folder as the engine executable
```

Then compile to generate your executable.

If you are using Linux, then use `/` instead of `\\` as path separator

**Comment by perfectN00b** [comment]
Thank you very much! Great! This helps me further.

Wish you still a nice weekend.

**Comment by khalid-a-omar** [comment]
Glad to help :)
